{
 "title": "CRDB: Hardware",
 "time": { "from": "2024-08-30T06:40:38.278Z", "to": "2024-08-30T08:40:38.278Z" },
 "panels": [
  {
   "title": "CPU Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "crdb_dedicated_sys_cpu_combined_percent_normalized{job='cockroachdb'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory in use across all nodes",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "crdb_dedicated_sys_rss{job=\"cockroachdb\"}",
     "legendFormat": "{{instance}}"
    },
    {}
   ]
  },
  {
   "title": "Disk IOs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(crdb_dedicated_sys_host_disk_iopsinprogress{job=\"cockroachdb\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Ops In Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(crdb_dedicated_sys_host_disk_iopsinprogress{job=\"cockroachdb\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Disk Capacity",
   "type": "timeseries",
   "description": "Free disk space available to CockroachDB data.\n\n[How is this metric calculated?](https://www.cockroachlabs.com/docs/v21.1/ui-storage-dashboard.html#capacity-metrics)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "crdb_dedicated_capacity_available{job=\"cockroachdb\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(crdb_dedicated_sys_host_net_recv_bytes_total{job=\"cockroachdb\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(crdb_dedicated_sys_host_net_send_bytes_total{job=\"cockroachdb\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}